name: Build docker images

on:
  push:


jobs:
  docker:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{matrix.runner}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Core
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: ${{ matrix.arch }}
          build-args: "COMMIT=${{ github.sha }}"
          tags: |
            ghcr.io/noi-techpark/c3nav:${{ github.sha }}
            ghcr.io/noi-techpark/c3nav:${{github.ref_name}}-latest
          labels: |
            org.opencontainers.image.version=${{ github.sha }}
          annotations: |
            org.opencontainers.image.source="https://github.com/noi-techpark/c3nav"
            org.opencontainers.image.url="https://c3nav.de"
            org.opencontainers.image.authors="c3nav team"
            org.opencontainers.image.description="Indoor navigation for the Chaos Communication Congress and other events. - Core"
          cache-from: type=registry,ref=ghcr.io/noi-techpark/c3nav_cache:main
          cache-to: type=registry,ref=ghcr.io/noi-techpark/c3nav_cache:main,mode=max

      - name: Build and Push Tileserver
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/tileserver.dockerfile
          push: true
          platforms: ${{ matrix.arch }}
          build-args: "COMMIT=${{ github.sha }}"
          tags: |
            ghcr.io/noi-techpark/c3nav-tileserver:${{ github.sha }}
            ghcr.io/noi-techpark/c3nav-tileserver:${{github.ref_name}}-latest
          labels: |
            org.opencontainers.image.version=${{ github.sha }}
          annotations: |
            org.opencontainers.image.source="https://github.com/noi-techpark/c3nav"
            org.opencontainers.image.url="https://c3nav.de"
            org.opencontainers.image.authors="c3nav team"
            org.opencontainers.image.description="Indoor navigation for the Chaos Communication Congress and other events. - Tileserver"
          cache-from: type=registry,ref=ghcr.io/noi-techpark/c3nav_cache:tileserver_main
          cache-to: type=registry,ref=ghcr.io/noi-techpark/c3nav_cache:tileserver_main,mode=max
          
